# Aula 3 — Comparando 2012 x 2026 e cruzando com afazeres domésticos

Nesta aula:
1. Abrir e juntar as duas **Tabelas 5** (composição da desocupação por sexo, 2012 e 2026)
2. Comparar ano a ano (quem ganhou/perdeu participação)
3. Cruzar com a **Tabela 1.1.1** do IBGE (horas semanais de afazeres domésticos, 2022)

In [1]:
import pandas as pd

## 1. Abrir a Tabela 5 de 2012

O CSV usa `;` como separador de coluna e `,` como separador decimal (padrão brasileiro) — por isso `sep=";"` e `decimal=","`. O `encoding="utf-8-sig"` remove o caractere invisível (BOM) que aparece no início do arquivo quando ele foi salvo pelo Excel.

In [2]:
path_2012 = "Tabela5-sem_emprego_2012.csv"

t2012 = pd.read_csv(path_2012, sep=";", decimal=",", encoding="utf-8-sig")

In [3]:
t2012

,Sigla,Código,Estado,Desocupados - homens (2012 T1),Desocupados - mulheres (2012 T1)
0,AC,12,Acre,45.3,54.7
1,AL,27,Alagoas,44.7,55.3
2,AM,13,Amazonas,47.5,52.5
3,AP,16,Amapá,48.1,51.9
4,BA,29,Bahia,43.8,56.2
5,CE,23,Ceará,51.1,48.9
6,DF,53,Distrito Federal,41.0,59.0
7,ES,32,Espírito Santo,46.4,53.6
8,GO,52,Goiás,41.0,59.0
9,MA,21,Maranhão,47.2,52.8
10,MG,31,Minas Gerais,43.1,56.9
11,MS,50,Mato Grosso do Sul,47.2,52.8
12,MT,51,Mato Grosso,44.1,55.9
13,PA,15,Pará,43.2,56.8
14,PB,25,Paraíba,44.4,55.6
15,PE,26,Pernambuco,43.9,56.1
16,PI,22,Piauí,51.2,48.8
17,PR,41,Paraná,40.3,59.7
18,RJ,33,Rio de Janeiro,44.2,55.8
19,RN,24,Rio Grande do Norte,51.0,49.0
20,RO,11,Rondônia,43.4,56.6
21,RR,14,Roraima,41.8,58.2
22,RS,43,Rio Grande do Sul,42.8,57.2
23,SC,42,Santa Catarina,42.7,57.3
24,SE,28,Sergipe,46.5,53.5
25,SP,35,São Paulo,45.4,54.6
26,TO,17,Tocantins,55.3,44.7

## 2. Abrir a Tabela 5 de 2026

Mesma lógica de leitura.

In [4]:
path_2026 = "Tabela5-sem_emprego_2026.csv"

t2026 = pd.read_csv(path_2026, sep=";", decimal=",", encoding="utf-8-sig")

In [5]:
t2026

,Sigla,Código,Estado,Desocupados - homens (2026 T1),Desocupados - mulheres (2026 T1)
0,AC,12,Acre,53.2,46.8
1,AL,27,Alagoas,50.7,49.3
2,AM,13,Amazonas,46.8,53.2
3,AP,16,Amapá,51.1,48.9
4,BA,29,Bahia,44.7,55.3
5,CE,23,Ceará,52.7,47.3
6,DF,53,Distrito Federal,47.9,52.1
7,ES,32,Espírito Santo,47.5,52.5
8,GO,52,Goiás,47.5,52.5
9,MA,21,Maranhão,49.1,50.9
10,MG,31,Minas Gerais,48.6,51.4
11,MS,50,Mato Grosso do Sul,45.3,54.7
12,MT,51,Mato Grosso,42.8,57.2
13,PA,15,Pará,48.3,51.7
14,PB,25,Paraíba,48.9,51.1
15,PE,26,Pernambuco,48.7,51.3
16,PI,22,Piauí,55.1,44.9
17,PR,41,Paraná,46.3,53.7
18,RJ,33,Rio de Janeiro,45.4,54.6
19,RN,24,Rio Grande do Norte,48.2,51.8
20,RO,11,Rondônia,33.0,67.0
21,RR,14,Roraima,43.4,56.6
22,RS,43,Rio Grande do Sul,47.4,52.6
23,SC,42,Santa Catarina,44.6,55.4
24,SE,28,Sergipe,40.3,59.7
25,SP,35,São Paulo,46.2,53.8
26,TO,17,Tocantins,46.2,53.8

## 3. Juntar as duas tabelas

Repare que `t2012` e `t2026` têm as mesmas colunas **Sigla**, **Código** e **Estado** — é isso que usamos como chave do `merge`. As colunas de valor (homens/mulheres) têm nomes diferentes em cada tabela (`... 2012 T1` vs `... 2026 T1`), então o `merge` não cria conflito: as duas ficam lado a lado.

In [6]:
comp = t2012.merge(t2026, on=["Sigla", "Código", "Estado"], how="inner")
comp

,Sigla,Código,Estado,Desocupados - homens (2012 T1),Desocupados - mulheres (2012 T1),Desocupados - homens (2026 T1),Desocupados - mulheres (2026 T1)
0,AC,12,Acre,45.3,54.7,53.2,46.8
1,AL,27,Alagoas,44.7,55.3,50.7,49.3
2,AM,13,Amazonas,47.5,52.5,46.8,53.2
3,AP,16,Amapá,48.1,51.9,51.1,48.9
4,BA,29,Bahia,43.8,56.2,44.7,55.3
5,CE,23,Ceará,51.1,48.9,52.7,47.3
6,DF,53,Distrito Federal,41.0,59.0,47.9,52.1
7,ES,32,Espírito Santo,46.4,53.6,47.5,52.5
8,GO,52,Goiás,41.0,59.0,47.5,52.5
9,MA,21,Maranhão,47.2,52.8,49.1,50.9
10,MG,31,Minas Gerais,43.1,56.9,48.6,51.4
11,MS,50,Mato Grosso do Sul,47.2,52.8,45.3,54.7
12,MT,51,Mato Grosso,44.1,55.9,42.8,57.2
13,PA,15,Pará,43.2,56.8,48.3,51.7
14,PB,25,Paraíba,44.4,55.6,48.9,51.1
15,PE,26,Pernambuco,43.9,56.1,48.7,51.3
16,PI,22,Piauí,51.2,48.8,55.1,44.9
17,PR,41,Paraná,40.3,59.7,46.3,53.7
18,RJ,33,Rio de Janeiro,44.2,55.8,45.4,54.6
19,RN,24,Rio Grande do Norte,51.0,49.0,48.2,51.8
20,RO,11,Rondônia,43.4,56.6,33.0,67.0
21,RR,14,Roraima,41.8,58.2,43.4,56.6
22,RS,43,Rio Grande do Sul,42.8,57.2,47.4,52.6
23,SC,42,Santa Catarina,42.7,57.3,44.6,55.4
24,SE,28,Sergipe,46.5,53.5,40.3,59.7
25,SP,35,São Paulo,45.4,54.6,46.2,53.8
26,TO,17,Tocantins,55.3,44.7,46.2,53.8

### Pergunta 1
Em quais estados a participação **das mulheres** entre os desocupados **mais aumentou** de 2012 para 2026?

*Dica: crie uma coluna com a diferença entre a coluna de mulheres de 2026 e a de 2012, e ordene.*

In [7]:
comp["variacao_mulheres"] = (
    comp["Desocupados - mulheres (2026 T1)"] - comp["Desocupados - mulheres (2012 T1)"]
)

maior_aumento = comp.sort_values("variacao_mulheres", ascending=False)[
    ["Estado", "variacao_mulheres"]
]

maior_aumento.head(5)

                 Estado  variacao_mulheres
20             Rondônia               10.4
26            Tocantins                9.1
24              Sergipe                6.2
19  Rio Grande do Norte                2.8
11   Mato Grosso do Sul                1.9

### Pergunta 2
Em **quantos** estados a participação das mulheres **diminuiu** entre 2012 e 2026?

In [8]:
qtd_diminuiu = (comp["variacao_mulheres"] < 0).sum()

print(f"Participação das mulheres diminuiu em {qtd_diminuiu} de {len(comp)} estados.")

Participação das mulheres diminuiu em 20 de 27 estados.

## 4. Cruzar com a Tabela 1.1.1 (horas de afazeres domésticos)

Reaproveitamos a leitura da Aula 2 para carregar `indicador_1` a partir do `.xls` do IBGE (pulando título, cabeçalho em várias linhas e rodapé).

In [9]:
path_ibge = "Tabela_1_1_1.xls"

bruto = pd.read_excel(path_ibge, engine="xlrd", header=None)

indicador_1 = bruto.iloc[8:41].copy()
indicador_1.columns = [
    "uf_regiao",
    "total",
    "total_branca",
    "total_preta_parda",
    "homem_branca",
    "homem_preta_parda",
    "mulher_branca",
    "mulher_preta_parda",
]
indicador_1 = indicador_1.reset_index(drop=True)

for col in indicador_1.columns[1:]:
    indicador_1[col] = pd.to_numeric(indicador_1[col], errors="coerce")

indicador_1

,uf_regiao,total,total_branca,total_preta_parda,homem_branca,homem_preta_parda,mulher_branca,mulher_preta_parda
0,Brasil,16.985781,16.545930,17.333142,11.705136,11.746330,20.404106,22.037998
1,Norte,16.187037,15.925246,16.256032,11.588653,11.514646,19.295780,20.534188
2,Rondônia,17.014162,16.727733,17.101523,12.111127,12.544080,20.412887,21.061410
3,Acre,13.606903,13.806929,13.541399,10.796120,9.686983,16.130352,16.710754
4,Amazonas,16.807290,15.987545,16.995493,12.233043,12.822584,18.764969,20.716986
5,Roraima,13.639257,13.651755,13.633606,10.814803,10.476601,16.135877,16.560244
6,Pará,16.474268,16.181627,16.560239,11.524306,11.026707,19.835110,21.591144
7,Amapá,13.586656,14.389180,13.415091,11.116821,10.749444,16.648579,15.908487
8,Tocantins,15.815781,15.701788,15.768728,10.733863,11.682616,19.663713,19.629399
9,Nordeste,18.499396,18.151700,18.610911,11.723907,11.848436,22.744666,23.716716
10,Maranhão,16.669614,16.421773,16.708894,11.665173,11.437359,19.881056,20.739589
11,Piauí,17.960366,16.948094,18.231789,12.258324,11.204814,20.494063,23.695440
12,Ceará,19.499293,18.527120,19.882469,12.186936,12.821323,23.019718,24.952274
13,Rio Grande do Norte,18.307740,18.101853,18.445218,11.166909,11.086286,23.547080,24.422884
14,Paraíba,18.920816,18.887920,18.945306,12.480204,12.400831,23.642936,24.035650
15,Pernambuco,19.306249,18.950219,19.418444,12.312833,12.868821,23.357880,24.243396
16,Alagoas,20.217129,19.165111,20.560451,12.121839,13.357160,24.093655,25.856637
17,Sergipe,18.826541,17.264294,19.317934,10.830511,11.270341,21.740902,25.637681
18,Bahia,17.849776,17.538007,17.935566,10.551673,10.982808,22.572730,23.217119
19,Sudeste,17.104218,16.834863,17.397989,11.933522,12.180843,20.732969,21.990431
20,Minas Gerais,17.502141,17.179387,17.707564,11.319720,11.619120,22.186650,23.075751
21,Espírito Santo,17.111106,16.510610,17.478861,11.798571,12.017589,20.464462,22.196626
22,Rio de Janeiro,16.716263,16.097467,17.243060,12.000036,12.864896,19.203741,20.957728
23,São Paulo,17.071295,16.964437,17.255480,12.123044,12.235200,20.771186,21.767620
24,Sul,15.527769,15.570983,15.406088,11.546629,11.159487,19.012969,19.338734
25,Paraná,15.390122,15.453295,15.307289,11.240085,10.815611,18.896661,19.365380
26,Santa Catarina,16.039355,16.124417,15.616235,12.339052,11.517342,19.414764,19.646573
27,Rio Grande do Sul,15.356709,15.337269,15.448203,11.308447,11.519941,18.868230,19.107720
28,Centro-Oeste,15.000763,14.826985,15.078025,10.546799,10.332059,18.220683,19.331040
29,Mato Grosso do Sul,15.309783,14.902105,15.567204,10.446213,11.126920,18.593200,19.542761
30,Mato Grosso,14.239989,14.083513,14.270209,9.479654,9.265734,17.782825,18.695923
31,Goiás,15.186471,14.962622,15.296966,10.636424,10.531883,18.440842,19.587913
32,Distrito Federal,15.096351,15.061306,15.126295,11.377952,10.481279,17.738123,19.307332

Os nomes de estado batem: `comp["Estado"]` (Tabela 5) usa o mesmo texto que `indicador_1["uf_regiao"]` (ex.: `"Minas Gerais"`, `"Amapá"`). Isso permite o `merge` mesmo com nomes de coluna diferentes, usando `left_on` / `right_on`.

**Atenção:** `indicador_1` também tem linhas de região (`"Norte"`, `"Nordeste"`...) e `"Brasil"`, que não existem em `comp` — por isso usamos `how="inner"`, que descarta automaticamente o que não casa.

In [10]:
final = comp.merge(indicador_1, left_on="Estado", right_on="uf_regiao", how="inner")

final[["Estado", "variacao_mulheres", "total"]]

                 Estado  variacao_mulheres      total
0                  Acre               -7.9  13.606903
1               Alagoas               -6.0  20.217129
2              Amazonas                0.7  16.807290
3                 Amapá               -3.0  13.586656
4                 Bahia               -0.9  17.849776
5                 Ceará               -1.6  19.499293
6      Distrito Federal               -6.9  15.096351
7        Espírito Santo               -1.1  17.111106
8                 Goiás               -6.5  15.186471
9              Maranhão               -1.9  16.669614
10         Minas Gerais               -5.5  17.502141
11   Mato Grosso do Sul                1.9  15.309783
12          Mato Grosso                1.3  14.239989
13                 Pará               -5.1  16.474268
14              Paraíba               -4.5  18.920816
15           Pernambuco               -4.8  19.306249
16                Piauí               -3.9  17.960366
17               Paraná               -6.0  15.390122
18       Rio de Janeiro               -1.2  16.716263
19  Rio Grande do Norte                2.8  18.307740
20             Rondônia               10.4  17.014162
21              Roraima               -1.6  13.639257
22    Rio Grande do Sul               -4.6  15.356709
23       Santa Catarina               -1.9  16.039355
24              Sergipe                6.2  18.826541
25            São Paulo               -0.8  17.071295
26            Tocantins                9.1  15.815781

### Pergunta final
Existe relação entre o **aumento da desocupação feminina** (2012→2026) e as **horas semanais de afazeres domésticos**? Calcule a correlação entre `variacao_mulheres` e `total`.

In [11]:
correlacao = final["variacao_mulheres"].corr(final["total"])

print(f"Correlação entre variação da desocupação feminina e horas de afazeres domésticos: {correlacao:.2f}")

Correlação entre variação da desocupação feminina e horas de afazeres domésticos: 0.10

A correlação sai **próxima de zero** — ou seja, nesses dados, o quanto a participação feminina na desocupação mudou de 2012 a 2026 **não** parece estar associado ao número de horas semanais dedicadas a afazeres domésticos em cada estado. São duas dimensões distintas da desigualdade de gênero, que aqui não caminham juntas.